require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PropertyPicturesController do

  # This should return the minimal set of attributes required to create a valid
  # PropertyPicture. As you add validations to PropertyPicture, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "title" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PropertyPicturesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all property_pictures as @property_pictures" do
      property_picture = PropertyPicture.create! valid_attributes
      get :index, {}, valid_session
      assigns(:property_pictures).should eq([property_picture])
    end
  end

  describe "GET show" do
    it "assigns the requested property_picture as @property_picture" do
      property_picture = PropertyPicture.create! valid_attributes
      get :show, {:id => property_picture.to_param}, valid_session
      assigns(:property_picture).should eq(property_picture)
    end
  end

  describe "GET new" do
    it "assigns a new property_picture as @property_picture" do
      get :new, {}, valid_session
      assigns(:property_picture).should be_a_new(PropertyPicture)
    end
  end

  describe "GET edit" do
    it "assigns the requested property_picture as @property_picture" do
      property_picture = PropertyPicture.create! valid_attributes
      get :edit, {:id => property_picture.to_param}, valid_session
      assigns(:property_picture).should eq(property_picture)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PropertyPicture" do
        expect {
          post :create, {:property_picture => valid_attributes}, valid_session
        }.to change(PropertyPicture, :count).by(1)
      end

      it "assigns a newly created property_picture as @property_picture" do
        post :create, {:property_picture => valid_attributes}, valid_session
        assigns(:property_picture).should be_a(PropertyPicture)
        assigns(:property_picture).should be_persisted
      end

      it "redirects to the created property_picture" do
        post :create, {:property_picture => valid_attributes}, valid_session
        response.should redirect_to(PropertyPicture.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved property_picture as @property_picture" do
        # Trigger the behavior that occurs when invalid params are submitted
        PropertyPicture.any_instance.stub(:save).and_return(false)
        post :create, {:property_picture => { "title" => "invalid value" }}, valid_session
        assigns(:property_picture).should be_a_new(PropertyPicture)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PropertyPicture.any_instance.stub(:save).and_return(false)
        post :create, {:property_picture => { "title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested property_picture" do
        property_picture = PropertyPicture.create! valid_attributes
        # Assuming there are no other property_pictures in the database, this
        # specifies that the PropertyPicture created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PropertyPicture.any_instance.should_receive(:update_attributes).with({ "title" => "MyString" })
        put :update, {:id => property_picture.to_param, :property_picture => { "title" => "MyString" }}, valid_session
      end

      it "assigns the requested property_picture as @property_picture" do
        property_picture = PropertyPicture.create! valid_attributes
        put :update, {:id => property_picture.to_param, :property_picture => valid_attributes}, valid_session
        assigns(:property_picture).should eq(property_picture)
      end

      it "redirects to the property_picture" do
        property_picture = PropertyPicture.create! valid_attributes
        put :update, {:id => property_picture.to_param, :property_picture => valid_attributes}, valid_session
        response.should redirect_to(property_picture)
      end
    end

    describe "with invalid params" do
      it "assigns the property_picture as @property_picture" do
        property_picture = PropertyPicture.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PropertyPicture.any_instance.stub(:save).and_return(false)
        put :update, {:id => property_picture.to_param, :property_picture => { "title" => "invalid value" }}, valid_session
        assigns(:property_picture).should eq(property_picture)
      end

      it "re-renders the 'edit' template" do
        property_picture = PropertyPicture.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PropertyPicture.any_instance.stub(:save).and_return(false)
        put :update, {:id => property_picture.to_param, :property_picture => { "title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested property_picture" do
      property_picture = PropertyPicture.create! valid_attributes
      expect {
        delete :destroy, {:id => property_picture.to_param}, valid_session
      }.to change(PropertyPicture, :count).by(-1)
    end

    it "redirects to the property_pictures list" do
      property_picture = PropertyPicture.create! valid_attributes
      delete :destroy, {:id => property_picture.to_param}, valid_session
      response.should redirect_to(property_pictures_url)
    end
  end

end
